# Generated by Django 3.2.25 on 2024-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('sinhala', 'Sinhala'), ('tamil', 'Tamil'), ('hindi', 'Hindi')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screening_type',
            field=models.CharField(choices=[('Now Screening', 'Now Screening'), ('Comming Soon', 'Comming Soon')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.CharField(choices=[('10 AM', '10 AM'), ('12 PM', '12 PM'), ('4 PM', '4 PM'), ('7 PM', '7 PM'), ('10 PM', '10 PM')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
