# Generated by Django 5.0.6 on 2024-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_type',
            field=models.CharField(choices=[('Now Screening', 'Now Screening'), ('Coming Soon', 'Coming Soon')], max_length=20, null=True),
        ),
    ]
