# Generated by Django 5.0.6 on 2024-06-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookedseat_movie_booked_seats'),
        ('myapp', '0011_alter_movie_screening_type'),
    ]

    operations = [
    ]
