# Generated by Django 5.0.6 on 2024-06-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Sinhala', 'Sinhala'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(choices=[('English', 'English'), ('Sinhala', 'Sinhala'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Musical Fantasy', 'Musical Fantasy'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
