# Generated by Django 5.0.6 on 2024-06-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_movie_screening_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('col', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='screening_type',
            field=models.CharField(choices=[('Now Screening', 'Now Screening'), ('Comming Soon', 'Comming Soon')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='myapp.bookedseat'),
        ),
    ]
