# Generated by Django 3.2.25 on 2024-06-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_movie_language_alter_movie_trailer_url_and_more'),
        ('myapp', '0012_merge_20240625_1049'),
    ]

    operations = [
    ]
